### ISSUE TITLE
thumbnail gif?

### ISSUE THREAD

**Issue by lindsayplatt** [USGS-VIZLAB/hurricane-irma#35]
Loop through multiple time stamps to create a gif. Would be nice

**Comment by jordansread** [comment]
Did we verify that a gif works as a thumbnail? Do all sites we use support it? (twitter/FB/reddit)

**Comment by jordansread** [comment]
Guessing the size of the thumbnail may be the limiting factor if gifs are supported

**Comment by lindsayplatt** [comment]
^ seen gifs that are thumbnails on other sites. Was mostly meaning that we should create a gif out of the thumbnail images so that gif file could be used as the main content on instagram or something.
