### ISSUE TITLE
add forecasted stage?

### ISSUE THREAD

**Issue by jordansread** [USGS-VIZLAB/hurricane-irma#59]
and convert to stage (from discharge)

**Comment by dblodgett-usgs** [comment]
This should be implemented in a branch since its kinda a risky change that we'll want to look at.

**Comment by wdwatkins** [comment]
#61 brought in this data, it is connected to anything yet though.

**Comment by jordansread** [comment]
Data are in. we need to create a new issue in the future (Monday?) for how to implement including it. 

One of the things to think about is how to deal w/ future precip, which we don't have...does it just go blank?
do we not animate into the future, but should the future sparklines partially hidden (how they are incrementally revealed now)?
