### ISSUE TITLE
Add media query and provide appropriate view: landscape (desktop) or portrait (mobile)

### ISSUE THREAD

**Issue by jordansread** [USGS-VIZLAB/hurricane-irma#60]
I think our default view is great for mobile portrait, but not great for desktop. an easy fix is clipping the viewbox for desktop, and letting it scale. 

So "0 0 500 700" becomes "0 0 500 450" on desktop...

also, adjusting the fonts when making this switch would be good.

**Comment by mbucknell** [comment]
I can do this but I think I need to work with someone as to how we want the gages to look. They get cut off if I change the viewBox to the above.

**Comment by jordansread** [comment]
Mary, I think a better way to get it is to load/inject the svg to the DOM and choose from two svg versions to do this. Possible?

That way we can get the best layout for each and also filter some gages out of the mobile view

**Comment by jordansread** [comment]
See ajax injection part of https://zengenti.com/en-us/blog/authors/jasonalvis/intro-to-front-end-svgs.aspx

**Comment by mbucknell** [comment]
Closed by PR #84 and PR #85
