### ISSUE TITLE
on mobile, tapping a spark changes the class of the gage dot and it doesn't go back

### ISSUE THREAD

**Issue by jordansread** [USGS-VIZLAB/hurricane-irma#69]
See Harvey for a more exaggerated version of this

**Comment by wdwatkins** [comment]
Can we also make the gage dot turn yellow the way the sparkline does?  Looks like we actually make the corresponding gage less prominent when the sparkline is hovered on, and it is difficult to pick it out.

**Comment by mbucknell** [comment]
I think https://github.com/USGS-VIZLAB/hurricane-irma/pull/74 should fix this.

**Comment by jordansread** [comment]
setting up a way to test this now...

**Comment by jordansread** [comment]
verified fixed by @mbucknell in #74
