### ISSUE TITLE
use "_blank" in clicklink function.

### ISSUE THREAD

**Issue by dblodgett-usgs** [USGS-VIZLAB/hurricane-irma#71]
I'm not sure how to fix this, but it should be a no brainer for @mbucknell 

We pass `_blank` here: https://github.com/USGS-VIZLAB/hurricane-irma/blob/66048c98c9ac92940422545e136b493df651d886/layout/js/animate.js#L124

but don't use it in the vizlab clicklink function. Maybe this is an issue for vizlab? 
https://github.com/USGS-VIZLAB/vizlab/blob/765b5b59ebd5f42b3f1b9b1bad90f3bc47069318/inst/js/vizlab.js#L53

**Comment by mbucknell** [comment]
This is an issue with vizlab, it doesn't take a second parameter for the _blank. Could change the function in hurricane-irma to call ga directly and then make the call to open in a new tab rather than using the vizlab.clicklink function.  Any preferences, change locally or change vizlab?

**Comment by dblodgett-usgs** [comment]
We need to get it fixed one way or another. Maybe a temporary override and make sure it gets into the viz sprint next week?

**Comment by mbucknell** [comment]
Closed by PR #83
