### ISSUE TITLE
what are we doing with the "non-featured" gages?

### ISSUE THREAD

**Issue by jordansread** [USGS-VIZLAB/hurricane-irma#76]
Are we showing them? do we support any interactions with them?

If we aren't doing mouseovers or onClick events on them, we can massively shrink their contribution to the DOM by converting them from 1,000's of <circle/> elements, to a single <path/>

![image](https://user-images.githubusercontent.com/2349007/30253287-af53fb26-9647-11e7-94f1-67ddc826f10c.png)

depending on what we do w/ them, if they don't have interactions we should also lower their z-index so they aren't getting in the way of other mouse events.

**Comment by dblodgett-usgs** [comment]
I think we should really de-emphasize or remove them.They distract from the point of the viz.

**Comment by amrhoades** [comment]
I second Dave. Remove!

**Comment by dblodgett-usgs** [comment]
Done right @jread-usgs ?
