### ISSUE TITLE
create tagged URLs for various campaigns

### ISSUE THREAD

**Issue by jordansread** [USGS-VIZLAB/hurricane-irma#78]
Twitter, reddit, facebook, instagram

**Comment by jordansread** [comment]
And this should be related to the outreach plan

**Comment by wdwatkins** [comment]
Is the outreach plan written down somewhere?  And will there only be the main USGS facebook, twitter etc?  Or multiple accounts on each platform?

**Comment by dblodgett-usgs** [comment]
Done right @wdwatkins ?

**Comment by wdwatkins** [comment]
yes
